# Generated by Django 3.2 on 2023-01-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
